apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgc
  template:
    metadata:
      labels:
        app: sgc
    spec:
      volumes:
      - name: env-file
        hostPath:
          path: /home/sgc/sgc_env/.env
          type: FileOrCreate
      - name: sessions-dir
        persistentVolumeClaim:
          claimName: sgc-sessions-pvc
      - name: logs-dir
        persistentVolumeClaim:
          claimName: sgc-logs-pvc
      initContainers:
        - name: gen-env
          image: ldiufes/sgc:latest
          envFrom:
            - configMapRef:
                name: sgc-config
          args:
            - /bin/ash
            - -c
            - php genEnv.php && cat BUILD >> .env
          volumeMounts:
            - name: env-file
              mountPath: /www/.env
      containers:
        - name: sgc
          envFrom:
            - configMapRef:
                name: sgc-config
          image: ldiufes/sgc:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: env-file
              mountPath: /www/.env
            - name: sessions-dir
              mountPath: /www/storage/framework/sessions
            - name: logs-dir
              mountPath: /www/storage/logs
